Initial/product api
netology-code/netomerch-backend pull request #26
Opened 2021-11-03 13:12 UTC by Apodisation13

Сделал для продуктов и категорий.

Проверил для get, post, patch, delete, админ\юзер\аноним.

2021-11-03 13:20 UTC, Pronich commented on neto_merch/requests.http
> +# КАТЕГОРИИ!!!
А весь этот файл - это тестовые запросы? Кажется лучше будет, если мы потом напишем Unit-tests для проверки.

2021-11-03 13:22 UTC, Apodisation13 commented on neto_merch/requests.http
> +# КАТЕГОРИИ!!!
Да, это тестовые запросы. Потом добавим тесты) Сейчас каждый сможет проверить по ним, у кого платная версия пайчарма...

2021-11-03 13:36 UTC, Pronich commented on neto_merch/requests.http
> +# КАТЕГОРИИ!!!
Лучше тогда проект в Postman сделать. Уверен, что не у всех платная и будет лишний файл. А Postman доступен всем и там можно перекидывать проект от человека к человеку

2021-11-03 14:18 UTC, Pronich requested changes

2021-11-03 14:18 UTC, Pronich commented on neto_merch/shop/admin.py
> +admin.site.register(Category)
Ты пока просто добавил это в админку? Связи делать будем, когда модели уже сделаем?

2021-11-03 14:18 UTC, Pronich commented on neto_merch/shop/views.py
> +class CategoryViewSet(BaseViewSet, ModelViewSet):
1. Сейчас этот метод возвращает все данные по всем категориям. Нужно ли это? Все-таки давай попробуем логику разобрать:
* Мы получаем все категории - когда заходим на сайт. Но более точные данные необходимо будет получать в момент прокаливания в категорию (или нет - это вопрос для обсуждения)
* Всю информацию по категории скорее всего получим при определенном запросе
2. Получение продуктов аналогично. Зачем на фронт возвращать огромную портянку данных по каждому продукту?
* Должна быть связь с категорией, которую выбрал клиент - для отображения списка возможных товаров
* Должен быть метод получения определенного товара и получения по этому товару всех данных (для отображения карточки продукта)

2021-11-03 14:19 UTC, Pronich commented on neto_merch/shop/views.py
> +class CategoryViewSet(BaseViewSet, ModelViewSet):
Да, я понимаю, что пока нет модели это сложно сделать, но базовую логику можно написать через queryparams

2021-11-03 16:49 UTC, Apodisation13 commented on neto_merch/requests.http
> +# КАТЕГОРИИ!!!
Принято, завтра разберусь с постмэном

2021-11-03 16:50 UTC, Apodisation13 commented on neto_merch/shop/admin.py
> +admin.site.register(Category)
Не очень понимаю, какие связи?

2021-11-03 16:51 UTC, Apodisation13 commented on neto_merch/shop/views.py
> +class CategoryViewSet(BaseViewSet, ModelViewSet):
Ушел думать )) тут сразу не могу сказать)

2021-11-03 18:39 UTC, Pronich commented on neto_merch/shop/admin.py
> +admin.site.register(Category)
Ну мы для добавления продукта должны указать, к какой категории он принадлежит. Не через Id категории это делать ведь. Соответственно можно сделать админку так, что у нас есть возможность добавить категорию, а при добавлении продукта эту категорию выбрать. 

Можешь посмотреть [тут](https://github.com/Pronich/c5_l4_orm2/blob/master/m2m-relations/articles/admin.py). Можешь даже запустить этот джанго проект, создать суперадмина и посмотреть, как будет выглядеть.

2021-11-03 18:41 UTC, Apodisation13 commented on neto_merch/shop/admin.py
> +admin.site.register(Category)
А, понял!) Посмотрю, спасибо!

2021-11-03 18:43 UTC, Pronich commented on neto_merch/shop/admin.py
> +admin.site.register(Category)
Делается это через Inline formset. Скинул презу нетологии в телеге. С 28 страницы.

2021-11-04 22:35 UTC, Pronich commented on neto_merch/shop/views.py
> +class CategoryViewSet(BaseViewSet, ModelViewSet):
А еще, т.к. DRF реализует только на ReadOnly можно использовать https://www.django-rest-framework.org/api-guide/viewsets/#readonlymodelviewset

2021-11-07 19:14 UTC, merged