Reviews/review
netology-code/netomerch-backend pull request #70
Opened 2021-11-30 14:09 UTC by Pronich

Что изменил. 

1. CICD вынес почту в Secrets
2. Изменил модель Accounts  и админку после прошлого ревью
3. Посмотрел email
4. Изменил Products
    1. Удалил ItemProperty
    2. Изменил отображение админки
5. Поправил немного Settings
6. Исправил Tests. Добавил комменты и удалил тесты на ItemProperty

Ребята, я все сломал! Посмотрите и дайте фидбек

2021-12-01 10:06 UTC, Apodisation13 commented on netomerch/config/settings.py
> +    "rest_framework",
Мне кажется, зря ты удаляешь fixme, ведь это специальная пометка для обсуждения, чтобы не забыть...

2021-12-01 11:29 UTC, Pronich commented on netomerch/config/settings.py
> +    "rest_framework",
Я это сделал, т.к. все, что там написано - уже разделено. Да и так понятно, зачем это и как используется. Но можно и вернуть.

2021-12-02 06:02 UTC, mikepro-alfamail-ru commented on netomerch/apps/email/tasks.py
> +    h.ignore_images = True  # TODO: Точно хотим игнорировать картинки?
Этот класс используется для генерации чистого текста на основе хтмл. Чистый текст кладется в письмо на всякий случай. Мало ли у кого нет графического почтового клиента -) Так что думаю, да, хотим.

2021-12-02 20:57 UTC, vdumchiviy requested changes

2021-12-02 20:57 UTC, vdumchiviy commented on netomerch/apps/accounts/models.py
>  class Customer(AbstractUser):
Предлагаю всё-таки более универсально - User

2021-12-02 20:57 UTC, vdumchiviy commented on netomerch/apps/products/models.py
> +    description = models.TextField(blank=True, null=True)  # FIXME: Кажется описания не будет
Просто отдавать не будем, уверен, что описание понадобится. К тому же я по тому списку достаточно красивый текст "наваял", должнО получится красиво

2021-12-02 20:57 UTC, vdumchiviy commented on netomerch/apps/reviews/models.py
> +    orders_item = models.ForeignKey(ItemConnections, blank=False, on_delete=models.CASCADE, related_name='reviews')
Предлагаю оставить в виде пары Заказ-Итем

2021-12-02 20:57 UTC, vdumchiviy commented on netomerch/apps/reviews/models.py
> +        return f"review {self.id}"
Давай сделаем, что б было нормальное название итема - просто номер ревью одиноко выглядит

2021-12-02 20:57 UTC, vdumchiviy commented on netomerch/apps/reviews/serializers.py
> +        fields = ('author', 'email', 'text', 'orders_item')
Считаю, что нужно вернуться к старому варианту (связка Ордер-Итем), только убрать валидацию на NULL для тех полей, у которых это на уровне модели проверяется

2021-12-02 20:57 UTC, vdumchiviy commented on netomerch/apps/reviews/views.py
> +    # def create(self, request, *args, **kwargs):  # TODO: Я пока закомментил этот код, потому что не понимаю его цель
Цель - Отправка сообщения для модерирования

2021-12-05 10:12 UTC, closed without merging